disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Nuremberg Juggling Convention"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Nuremberg Juggling Convention"
  headline = "14.-16.11.2025"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
  
