disabled = false
languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "Nürnberger Jonglierconvention"

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
   name = "14. Nürnberger Jonglierconvention"
   headline = "14.-16.11.2025"
#   email = "youremail@example.com"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96

