# -- Main Menu --

[[main]]
  name = "Direction"
  pageRef = "direction"
  weight = 10

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:info@jonglierconvention.de"
  weight = 200

# -- Footer Menu --
[[footer]]
  name = "Legal Notice"
  pageRef = "impressum"
  weight = 997

[[footer]]
  name = "Privacy"
  pageRef = "privacy"
  weight = 998

[[footer]]
  name = "info@jonglierconvention.de"
  url = "mailto:info@jonglierconvention.de"
  weight = 999
